'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class oa_patient
    Public Property oa_patient_id As Long
    Public Property oa_patient_nir As Nullable(Of Long)
    Public Property oa_patient_nir_modulo As Nullable(Of Integer)
    Public Property oa_patient_INS As Nullable(Of Long)
    Public Property oa_patient_prenom As String
    Public Property oa_patient_nom As String
    Public Property oa_patient_nom_usuel As String
    Public Property oa_patient_nom_marital As String
    Public Property oa_patient_date_naissance As Nullable(Of Date)
    Public Property oa_patient_lieu_naissance As String
    Public Property oa_patient_taille As Nullable(Of Integer)
    Public Property oa_patient_genre_id As String
    Public Property oa_patient_profession As String
    Public Property oa_patient_adresse1 As String
    Public Property oa_patient_adresse2 As String
    Public Property oa_patient_code_postal As String
    Public Property oa_patient_ville As String
    Public Property oa_patient_tel1 As String
    Public Property oa_patient_tel2 As String
    Public Property oa_patient_email As String
    Public Property oa_patient_date_entree_oasis As Nullable(Of Date)
    Public Property oa_patient_date_sortie_oasis As Nullable(Of Date)
    Public Property oa_patient_commentaire_sortie As String
    Public Property oa_patient_date_deces As Nullable(Of Date)
    Public Property oa_patient_site_id As Nullable(Of Long)
    Public Property oa_patient_siege_id As Nullable(Of Long)
    Public Property oa_patient_unite_sanitaire_id As Nullable(Of Long)
    Public Property oa_patient_pharmacie_id As Nullable(Of Long)
    Public Property oa_patient_synthese_date_maj As Nullable(Of Date)
    Public Property oa_patient_couverture_internet As Nullable(Of Boolean)
    Public Property oa_patient_creation_interne As String
    Public Property oa_patient_date_interface_entrante As Nullable(Of Date)
    Public Property oa_patient_date_interface_sortante As Nullable(Of Date)
    Public Property oa_patient_blocage_medical As Nullable(Of Boolean)

End Class
