'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class oa_patient_ordonnance_detail
    Public Property oa_ordonnance_ligne_id As Long
    Public Property oa_ordonnance_id As Nullable(Of Long)
    Public Property oa_ordonnance_traitement As Nullable(Of Boolean)
    Public Property oa_traitement_id As Nullable(Of Long)
    Public Property oa_traitement_ordre_affichage As Nullable(Of Integer)
    Public Property oa_traitement_ald As Nullable(Of Boolean)
    Public Property oa_traitement_a_delivrer As Nullable(Of Boolean)
    Public Property oa_traitement_medicament_cis As Nullable(Of Long)
    Public Property oa_traitement_medicament_dci As String
    Public Property oa_traitement_date_debut As Nullable(Of Date)
    Public Property oa_traitement_date_fin As Nullable(Of Date)
    Public Property oa_traitement_duree As Nullable(Of Integer)
    Public Property oa_traitement_posologie As String
    Public Property oa_traitement_posologie_base As String
    Public Property oa_traitement_posologie_rythme As Nullable(Of Integer)
    Public Property oa_traitement_posologie_matin As Nullable(Of Integer)
    Public Property oa_traitement_posologie_midi As Nullable(Of Integer)
    Public Property oa_traitement_posologie_apres_midi As Nullable(Of Integer)
    Public Property oa_traitement_posologie_soir As Nullable(Of Integer)
    Public Property oa_traitement_fraction_matin As String
    Public Property oa_traitement_fraction_midi As String
    Public Property oa_traitement_fraction_apres_midi As String
    Public Property oa_traitement_fraction_soir As String
    Public Property oa_traitement_posologie_commentaire As String
    Public Property oa_traitement_commentaire As String
    Public Property oa_traitement_fenetre As Nullable(Of Boolean)
    Public Property oa_traitement_fenetre_date_debut As Nullable(Of Date)
    Public Property oa_traitement_fenetre_date_fin As Nullable(Of Date)
    Public Property oa_traitement_inactif As Nullable(Of Boolean)

End Class
