'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class oa_patient_ordonnance
    Public Property oa_ordonnance_id As Long
    Public Property oa_ordonnance_patient_id As Long
    Public Property oa_ordonnance_utilisateur_creation As Long
    Public Property oa_ordonnance_date_creation As Date
    Public Property oa_ordonnance_date_validation As Nullable(Of Date)
    Public Property oa_ordonnance_user_validation As Nullable(Of Long)
    Public Property oa_ordonnance_signature As String
    Public Property oa_ordonnance_date_edition As Nullable(Of Date)
    Public Property oa_ordonnance_episode_id As Nullable(Of Long)
    Public Property oa_ordonnance_commentaire As String
    Public Property oa_ordonnance_renouvellement As Nullable(Of Integer)
    Public Property oa_ordonnance_inactif As Nullable(Of Boolean)

End Class
