'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class oa_utilisateur
    Public Property oa_utilisateur_id As Long
    Public Property oa_utilisateur_prenom As String
    Public Property oa_utilisateur_nom As String
    Public Property oa_utilisateur_profil_id As String
    Public Property oa_utilisateur_login As String
    Public Property oa_utilisateur_siege_id As Nullable(Of Long)
    Public Property oa_utilisateur_unite_sanitaire_id As Nullable(Of Long)
    Public Property oa_utilisateur_site_id As Nullable(Of Long)
    Public Property oa_utilisateur_date_entree As Nullable(Of Date)
    Public Property oa_utilisateur_date_sortie As Nullable(Of Date)
    Public Property oa_utilisateur_etat As String
    Public Property oa_password As String
    Public Property oa_utilisateur_admin As Nullable(Of Boolean)
    Public Property oa_utilisateur_telephone As String
    Public Property oa_utilisateur_fax As String
    Public Property oa_utilisateur_mail As String
    Public Property oa_utilisateur_rpps As String
    Public Property oa_utilisateur_password_is_unique_usage As Boolean
    Public Property cle_privee As String
    Public Property cle_publique As String

End Class
