'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class oasisEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=oasisEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property oa_patient() As DbSet(Of oa_patient)
    Public Overridable Property oa_patient_ordonnance() As DbSet(Of oa_patient_ordonnance)
    Public Overridable Property oa_patient_ordonnance_detail() As DbSet(Of oa_patient_ordonnance_detail)
    Public Overridable Property oa_utilisateur() As DbSet(Of oa_utilisateur)

End Class
