Public Class AnnuaireProfessionnelReference
    Property Cle_entree As Integer
    Property Typeidentifiant As Integer
    Property Identifiant As String
    Property IdentifiantNational As String
    Property CodeCiviliteExercice As String
    Property LibelleCiviliteExercice As String
    Property CodeCivilite As String
    Property LibelleCivilite As String
    Property NomExercice As String
    Property PrenomExercice As String
    Property CodeProfession As Integer
    Property LibelleProfession As String
    Property CodeCategorieProfessionnelle As String
    Property LibelleCategorieProfessionnelle As String
    Property CodeTypeSavoirFaire As String
    Property LibelleTypeSavoirFaire As String
    Property CodeSavoirFaire As String
    Property LibelleSavoirFaire As String
    Property CodeModeExercice As String
    Property LibelleModeExercice As String
    Property NumeroSiretSite As String
    Property NumeroSirenSite As String
    Property NumeroFinessSite As String
    Property NumeroFinessEtablissementJuridique As String
    Property IdentifiantTechniqueStructure As String
    Property RaisonSocialeSite As String
    Property EnseigneCommercialeSite As String
    Property ComplementDestinataireCoordonneeStructure As String
    Property ComplementPointGeographiqueCoordonneeStructure As String
    Property NumeroVoieCoordonneeStructure As String
    Property IndiceRepetitionVoieCoordonneeStructure As String
    Property CodeTypeVoieCoordonneeStructure As String
    Property LibelleTypeVoieCoordonneeStructure As String
    Property LibelleVoieCoordonneeStructure As String
    Property MentionDistributionCoordonneeStructure As String
    Property BureauCedexCoordonneeStructure As String
    Property CodePostalCoordonneeStructure As String
    Property CodeCommuneCoordonneeStructure As String
    Property LibelleCommuneCoordonneeStructure As String
    Property CodePaysCoordonneeStructure As String
    Property LibellePaysCoordonneeStructure As String
    Property TelephoneCoordonneeStructure As String
    Property Telephone2CoordonneeStructure As String
    Property TelepcopieCoordonneeStructure As String
    Property emailCoordonneeStructure As String
    Property CodeDepartementStructure As String
    Property LibelleDepartementStructure As String
    Property AncienIdentifiantStructure As String
    Property AutoriteEnregistrement As String
    Property CodeSecteurActivite As String
    Property LibelleSecteurActivite As String
    Property CodeSectionTableauPharmacien As String
    Property LibelleSectionTableauPharmacien As String

End Class
